name: Create tag

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create-tag:
    runs-on: ubuntu-latest
    # only merged pull requests that begin with 'release-' or 'hotfix-' must trigger this job
    if: github.event.pull_request.merged == true &&
      (startsWith(github.event.pull_request.head.ref, 'release-') || startsWith(github.event.pull_request.head.ref, 'hotfix-'))
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release-')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release-}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix-')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix-}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Create git tag
        run: git tag v${{ env.RELEASE_VERSION }}
      - name: Push git tag
        run: git push origin v${{ env.RELEASE_VERSION }}