
name: Tag Release
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create-tag:
    runs-on: ubuntu-latest
    # only merged pull requests that begin with 'release-' or 'hotfix-' must trigger this job
    if: github.event.pull_request.merged == true &&
      (startsWith(github.event.pull_request.head.ref, 'release-') || startsWith(github.event.pull_request.head.ref, 'hotfix-'))
    outputs:
      release_version:  ${{ steps.output-release-version.outputs.release_version }}
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release-')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release-}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix-')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix-}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "BkRepo Project Bot"
          git config user.email "bkrepo-project-bot@users.noreply.github.com"
      - name: Create git tag
        run: git tag v${{ env.RELEASE_VERSION }}
      - name: Push git tag
        run: git push origin v${{ env.RELEASE_VERSION }}
      - name: Output release version
        id: output-release-version
        run: echo "release_version=${{ env.RELEASE_VERSION }}" >> $GITHUB_OUTPUT
  frontend:
    needs: [create-tag]
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ needs.create-tag.outputs.release_version }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install project dependencies
        run: yarn --prefer-offline
      - run: yarn install && yarn start && yarn public
        working-directory: src/frontend
      - uses: actions/upload-artifact@v1
        with:
          name: frontend
          path: src/frontend/frontend

  backend:
    needs: [create-tag,frontend]
    name: Build backend and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ needs.create-tag.outputs.release_version }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      - name: Gradle Build Backend Service
        working-directory: src/backend
        run: |
          ./gradlew clean build
      - name: Create artifact - Step1:get Frontend
        uses: actions/download-artifact@v1
        with:
          name: frontend
          path: src/frontend/frontend
      - name: Create artifact - Step2:make package
        id: create-artifact
        run: |
          version="${{ needs.create-tag.outputs.release_version }})"
          ci_pkg_dir=/dev/shm/bkrepo ./scripts/packager-repo.sh "$version" bkrepo-slim.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: bkrepo
          path: bkrepo-slim.tar.gz          

  cloud-native:
    needs: [create-tag]
    name: Build image and helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ needs.create-tag.outputs.release_version }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      - name: Setup Docker -- CLOUD NATIVE
        uses: docker-practice/actions-setup-docker@master
      - name: Create Docker Image -- CLOUD NATIVE
        working-directory: scripts
        run: |
          version="${{ needs.create-tag.outputs.release_version }}"
          ./build-images.sh  -v $version --username ${{ secrets.DOCKER_USER }} \
          --password ${{ secrets.DOCKER_PASS }} -n ${{ secrets.DOCKER_NAMESPACE }} \
          -r ${{ secrets.DOCKER_HOST }} -p
      - name: Install Helm -- CLOUD NATIVE
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Package Helm Chart -- CLOUD NATIVE
        working-directory: support-files/kubernetes/charts
        run: |
          version="${{ needs.create-tag.outputs.release_version }}"
          ./build.sh --version $version --app-version $version
          mv bkrepo-$version.tgz bkrepo-charts.tgz
      - uses: actions/upload-artifact@v1
        with:
          name: bkrepo-chart
          path: support-files/kubernetes/charts/bkrepo-charts.tgz

  quick-start:
    needs: [create-tag,backend]
    name: Build all in one image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ needs.create-tag.outputs.release_version }}
      - name: download bkrepo
        uses: actions/download-artifact@v1
        id: download
        with:
          name: bkrepo
          path: ./
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Create Docker Image
        working-directory: scripts
        run: |
          version="${{ needs.create-tag.outputs.release_version }}"
          ./build-images.sh --all-in-one -v $version --username ${{ secrets.DOCKER_USER }} \
          --password ${{ secrets.DOCKER_PASS }} -n ${{ secrets.DOCKER_NAMESPACE }} \
          -r ${{ secrets.DOCKER_HOST }} --slim-package-path ../bkrepo-slim.tar.gz -p
          

  release-all:
    name: Release All
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [backend, cloud-native]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: bk-repo ${{ github.ref }}
          draft: true
          prerelease: true
      ## bkrepo
      - name: download bkrepo
        uses: actions/download-artifact@v1
        with:
          name: bkrepo
          path: ./
      - name: Upload Release Asset -- BKREPO
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bkrepo-slim.tar.gz
          asset_name: bkrepo-slim.tar.gz
          asset_content_type: application/gzip
      ## bkrepo helm chart
      - name: download bkrepo-chart
        uses: actions/download-artifact@v1
        with:
          name: bkrepo-chart
          path: ./
      - name: Upload Helm Chart -- CLOUD NATIVE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bkrepo-charts.tgz
          asset_name: bkrepo-charts.tgz
          asset_content_type: application/gzip